# Generated by Django 5.2.8 on 2025-11-11 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentralClientAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_domain', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('iteration_name', models.CharField(max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('hospital', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('central', 'Central Auth')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(upload_to='client_models/')),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.centralclientassignment')),
            ],
        ),
        migrations.AddField(
            model_name='centralclientassignment',
            name='central_auth',
            field=models.ForeignKey(limit_choices_to={'role': 'central'}, on_delete=django.db.models.deletion.CASCADE, related_name='central_auth_assignments', to='api.userprofile'),
        ),
        migrations.AddField(
            model_name='centralclientassignment',
            name='client',
            field=models.ForeignKey(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_assignments', to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='CentralAuthModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_name', models.CharField(max_length=255)),
                ('model_name', models.CharField(max_length=255)),
                ('dataset_domain', models.CharField(blank=True, max_length=255, null=True)),
                ('model_file', models.FileField(upload_to='central_models/')),
                ('version', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('central_auth', models.ForeignKey(limit_choices_to={'role': 'central'}, on_delete=django.db.models.deletion.CASCADE, to='api.userprofile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='centralclientassignment',
            unique_together={('client',)},
        ),
    ]
