# Generated by Django 5.2.8 on 2025-11-11 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='centralclientassignment',
            unique_together=set(),
        ),
    ]
